---
name: "tiller"
version: "0.9.2"
usage: "Please see https://github.com/rimusz/helm-tiller for usage"
description: "Start a Tiller server locally, aka Tillerless Helm"
command: "$HELM_PLUGIN_DIR/scripts/tiller.sh"
useTunnel: false
